[build]
  publish = "static"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  force = true
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
