[build]
  command = "pip install -r netlify/functions/api/requirements.txt"
  publish = "public"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  force = true
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
